### ISSUE TITLE
episode suggestion:

### ISSUE THREAD

**Issue by jnitin** [solo-io/hoot#14]
Envoy Filters

**Comment by harishb93** [comment]
+1 for EnvoyFilter on Istio
And some examples on RateLimiting other than the Gateway context rate-limiting example

**Comment by yuval-k** [comment]
we hope to do this in season 2, currently planned to fall 2021

**Comment by linsun** [comment]
I assume this is done, can we close it? @yuval-k

**Comment by linsun** [comment]
@jnitin https://www.youtube.com/watch?v=yOtEG1luTwU is the envoy filter episode.

**Comment by yuval-k** [comment]
Yes, this is done!
